project:
  type: website
  output-dir: docs

author:
  name: "Shalini Nair"
  url: "https://github.com/snair1809"

website:
  title: "The Data Dreamer"
  navbar:
    right:
      - text: "About"
        href: "about.qmd"
      - icon: github
        href: "https://github.com/snair1809"

format:
  html:
    theme: journal
    css: styles.css




